spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/asseblyVoteDB
management:
  endpoints:
    web:
      exposure:
        include: health
cpf:
  validator:
    api:
      url: https://api.invertexto.com
      token: 16008|9wpw0OYb6Lg9ZybbWlMqy2en33KfWmlS