spring:
  application:
    name: AssemblyVoteService
management:
  endpoints:
    web:
      exposure:
        include: health
cpf:
  validator:
    api:
      url: https://api.invertexto.com
      token: 16008|9wpw0OYb6Lg9ZybbWlMqy2en33KfWmlS # This should be an environment variable, but for didactic purposes, it will be used like this

aws:
  region: us-west-2